import { NextRequest, NextResponse } from 'next/server';
import { Endpoints } from '@/common/constants';
import { ApiContextEnum } from '@/common/enums';
import { apiFetch } from '@/common/helpers';

export interface RadioStationMetadata {
  id: string;
  stationId: string;
  name: string;
  description: string;
  coverUrl: string;
  language: string;
  category: 'featured' | 'artist' | 'mood' | 'devotional' | 'retro' | 'dance';
  listeners: number;
  gradient: string;
}

// ── Curated & JioSaavn WebRadio Station Catalog for ALL Languages (6-12 hr TTL) ───
const STATION_CATALOG_DATA: Record<string, RadioStationMetadata[]> = {
  Telugu: [
    {
      id: 'telugu-ultimate-dance-beats',
      stationId: 'telugu_ultimate_dance_beats',
      name: 'Ultimate Dance Beats',
      description: 'High voltage mass beats, EDM remixes & dancefloor bangers',
      coverUrl: 'https://c.saavncdn.com/editorial/TeluguEDMTelugu_20251006050054_500x500.jpg',
      language: 'Telugu',
      category: 'dance',
      listeners: 480000,
      gradient: 'from-orange-500/30 to-red-950/80',
    },
    {
      id: 'telugu-hyderabad-heartbeats',
      stationId: 'telugu_hyderabad_heartbeats',
      name: 'Hyderabad Heartbeats',
      description: 'Trending youth anthems, viral hits & city soundtracks',
      coverUrl: 'https://c.saavncdn.com/editorial/TrendingTeluguSongs_20260529073729_500x500.jpg',
      language: 'Telugu',
      category: 'featured',
      listeners: 590000,
      gradient: 'from-rose-500/30 to-pink-950/80',
    },
    {
      id: 'telugu-golden-melodies',
      stationId: 'telugu_golden_melodies',
      name: 'Golden Melodies',
      description: 'Heart-touching melody hits, acoustic chords & vocal magic',
      coverUrl: 'https://c.saavncdn.com/editorial/TeluguMelodyHits_20220617064213_500x500.jpg',
      language: 'Telugu',
      category: 'mood',
      listeners: 620000,
      gradient: 'from-emerald-500/30 to-teal-950/80',
    },
    {
      id: 'telugu-long-drive',
      stationId: 'telugu_long_drive',
      name: 'Long Drive Radio',
      description: 'Breezy melodies and road trip vibes for endless highway journeys',
      coverUrl: 'https://c.saavncdn.com/editorial/TravelCheddam_20251205063518_500x500.jpg',
      language: 'Telugu',
      category: 'mood',
      listeners: 430000,
      gradient: 'from-cyan-500/30 to-blue-950/80',
    },
    {
      id: 'telugu-saahore',
      stationId: 'telugu_saahore',
      name: 'Saahore',
      description: 'Mass hero elevation tracks, powerhouse BGM & heroism anthems',
      coverUrl: 'https://c.saavncdn.com/editorial/Let_sPlayPrabhasTelugu_20240628094353_500x500.jpg',
      language: 'Telugu',
      category: 'featured',
      listeners: 510000,
      gradient: 'from-amber-500/30 to-red-950/80',
    },
    {
      id: 'telugu-glass-party',
      stationId: 'telugu_glass_party',
      name: 'Glass Party',
      description: 'Full bass weekend party beats, item songs & celebrations',
      coverUrl: 'https://c.saavncdn.com/editorial/HousePartyTelugu_20260622091856_500x500.jpg',
      language: 'Telugu',
      category: 'dance',
      listeners: 390000,
      gradient: 'from-purple-500/30 to-indigo-950/80',
    },
    {
      id: 'telugu-mesmerizing-90s',
      stationId: 'telugu_mesmerizing_90s',
      name: 'Mesmerizing 90s',
      description: 'Cassette era nostalgic classics by SPB, Chithra & Mani Sharma',
      coverUrl: 'https://c.saavncdn.com/editorial/charts_Telugu1990s_157621_20240408063237_500x500.jpg',
      language: 'Telugu',
      category: 'retro',
      listeners: 530000,
      gradient: 'from-teal-500/30 to-slate-950/80',
    },
    {
      id: 'telugu-millennium-hits',
      stationId: 'telugu_millennium_hits',
      name: 'Millennium Hits',
      description: 'Iconic 2000s chartbusters, melody rhythms & youth anthems',
      coverUrl: 'https://c.saavncdn.com/editorial/charts_Telugu2000s_119381_20240408063159_500x500.jpg',
      language: 'Telugu',
      category: 'retro',
      listeners: 460000,
      gradient: 'from-blue-500/30 to-indigo-950/80',
    },
    {
      id: 'telugu-retro-spin',
      stationId: 'telugu_retro_spin',
      name: 'Retro Spin',
      description: '70s & 80s vintage vinyl classics and Maestro Ilaiyaraaja tunes',
      coverUrl: 'https://c.saavncdn.com/editorial/charts_Telugu1980s_173817_20240408063333_500x500.jpg',
      language: 'Telugu',
      category: 'retro',
      listeners: 380000,
      gradient: 'from-amber-500/30 to-amber-950/80',
    },
    {
      id: 'telugu-remix-mazaa',
      stationId: 'telugu_remix_mazaa',
      name: 'Remix Mazaa',
      description: 'Trending club edits, DJ mashups and non-stop bass drops',
      coverUrl: 'https://c.saavncdn.com/editorial/TeluguViralHits_20260814130344_500x500.jpg',
      language: 'Telugu',
      category: 'dance',
      listeners: 350000,
      gradient: 'from-fuchsia-500/30 to-purple-950/80',
    },
    {
      id: 'telugu-mi-inti-lakshmi',
      stationId: 'telugu_mi_inti_lakshmi',
      name: 'Mi Inti Lakshmi',
      description: 'Devotional suprabhatams, peaceful stotrams & morning prayers',
      coverUrl: 'https://c.saavncdn.com/editorial/VenkateswaraSwamyTelugu_20240730054019_500x500.jpg',
      language: 'Telugu',
      category: 'devotional',
      listeners: 570000,
      gradient: 'from-yellow-500/30 to-amber-950/80',
    },
    {
      id: 'telugu-ayyappa',
      stationId: 'telugu_ayyappa',
      name: 'Ayyappa Swamy Radio',
      description: 'Sacred Ayyappa deeksha songs, harivarasanam & devotional hymns',
      coverUrl: 'https://c.saavncdn.com/editorial/VenkateswaraSwamyTelugu_20240730054019_500x500.jpg',
      language: 'Telugu',
      category: 'devotional',
      listeners: 410000,
      gradient: 'from-orange-500/30 to-amber-950/80',
    },
    {
      id: 'telugu-om-sai-ram',
      stationId: 'telugu_om_sai_ram',
      name: 'Om Sai Ram Radio',
      description: 'Shirdi Sai Baba bhajans, aartis & soulful peaceful chants',
      coverUrl: 'https://c.saavncdn.com/editorial/VenkateswaraSwamyTelugu_20240730054019_500x500.jpg',
      language: 'Telugu',
      category: 'devotional',
      listeners: 360000,
      gradient: 'from-amber-500/30 to-yellow-950/80',
    },
    {
      id: 'telugu-nithyaardhana',
      stationId: 'telugu_nithyaardhana',
      name: 'Nithyaardhana',
      description: 'Daily divine pooja chants, Carnatic classical & Venkateswara devotional',
      coverUrl: 'https://c.saavncdn.com/editorial/VenkateswaraSwamyTelugu_20240730054019_500x500.jpg',
      language: 'Telugu',
      category: 'devotional',
      listeners: 490000,
      gradient: 'from-yellow-500/30 to-orange-950/80',
    },
  ],
  Hindi: [
    {
      id: 'hindi-bollywood-mega',
      stationId: 'hindi_bollywood_mega',
      name: 'Bollywood Mega Radio',
      description: 'Blockbuster chartbusters, superstar hits & current Bollywood sensations',
      coverUrl: 'https://c.saavncdn.com/editorial/HindiTop50_20231012120000_500x500.jpg',
      language: 'Hindi',
      category: 'featured',
      listeners: 780000,
      gradient: 'from-red-500/30 to-rose-950/80',
    },
    {
      id: 'hindi-pure-romance',
      stationId: 'hindi_pure_romance',
      name: 'Pure Romance Radio',
      description: 'Heartfelt love ballads, romantic duets by Arijit, Shreya & Atif',
      coverUrl: 'https://c.saavncdn.com/artists/Arijit_Singh_002_20230323062147_500x500.jpg',
      language: 'Hindi',
      category: 'mood',
      listeners: 890000,
      gradient: 'from-rose-500/30 to-pink-950/80',
    },
    {
      id: 'hindi-retro-bollywood',
      stationId: 'hindi_retro_bollywood',
      name: '90s Magic Bollywood',
      description: 'Evergreen 90s melodies by Kumar Sanu, Alka Yagnik & Udit Narayan',
      coverUrl: 'https://c.saavncdn.com/artists/Pritam_003_20230104094042_500x500.jpg',
      language: 'Hindi',
      category: 'retro',
      listeners: 640000,
      gradient: 'from-amber-500/30 to-orange-950/80',
    },
    {
      id: 'hindi-party-all-night',
      stationId: 'hindi_party_all_night',
      name: 'Party All Night Radio',
      description: 'High energy club bangers, Badshah rap & Bollywood dance anthems',
      coverUrl: 'https://c.saavncdn.com/artists/Neha_Kakkar_006_20200821105436_500x500.jpg',
      language: 'Hindi',
      category: 'dance',
      listeners: 530000,
      gradient: 'from-purple-500/30 to-indigo-950/80',
    },
    {
      id: 'hindi-sufi-ghazals',
      stationId: 'hindi_sufi_ghazals',
      name: 'Sufi & Soul Radio',
      description: 'Soulful Sufi anthems, soothing ghazals & acoustic poetry',
      coverUrl: 'https://c.saavncdn.com/artists/A_R_Rahman_002_20210322074345_500x500.jpg',
      language: 'Hindi',
      category: 'mood',
      listeners: 420000,
      gradient: 'from-emerald-500/30 to-teal-950/80',
    },
    {
      id: 'hindi-bhakti-sagar',
      stationId: 'hindi_bhakti_sagar',
      name: 'Bhakti Sagar Radio',
      description: 'Hanuman chalisa, Krishna bhajans, Shiv aartis & spiritual mantras',
      coverUrl: 'https://c.saavncdn.com/editorial/VenkateswaraSwamyTelugu_20240730054019_500x500.jpg',
      language: 'Hindi',
      category: 'devotional',
      listeners: 610000,
      gradient: 'from-orange-500/30 to-amber-950/80',
    },
  ],
  Tamil: [
    {
      id: 'tamil-kollywood-prime',
      stationId: 'tamil_kollywood_prime',
      name: 'Kollywood Prime Radio',
      description: 'Top trending Kollywood chartbusters, mass beats & Anirudh anthems',
      coverUrl: 'https://c.saavncdn.com/editorial/TamilTop50_20231012120000_500x500.jpg',
      language: 'Tamil',
      category: 'featured',
      listeners: 670000,
      gradient: 'from-cyan-500/30 to-blue-950/80',
    },
    {
      id: 'tamil-ilaiyaraaja-magic',
      stationId: 'tamil_ilaiyaraaja_magic',
      name: 'Maestro Ilaiyaraaja Radio',
      description: 'Timeless 80s & 90s classical orchestrations by Isaignani Ilaiyaraaja',
      coverUrl: 'https://c.saavncdn.com/artists/Ilaiyaraaja_002_20210322080436_500x500.jpg',
      language: 'Tamil',
      category: 'retro',
      listeners: 580000,
      gradient: 'from-amber-500/30 to-amber-950/80',
    },
    {
      id: 'tamil-u1-drugs',
      stationId: 'tamil_u1_drugs',
      name: 'U1 Drugs Radio',
      description: 'Cult melodies, nocturnal vibes & unforgettable BGM by Yuvan Shankar Raja',
      coverUrl: 'https://c.saavncdn.com/artists/Yuvan_Shankar_Raja_002_20230104094145_500x500.jpg',
      language: 'Tamil',
      category: 'mood',
      listeners: 490000,
      gradient: 'from-purple-500/30 to-indigo-950/80',
    },
    {
      id: 'tamil-kuthu-party',
      stationId: 'tamil_kuthu_party',
      name: 'Kuthu Fire Radio',
      description: 'Street festival dholak beats, dappankuthu bangers & mass celebrations',
      coverUrl: 'https://c.saavncdn.com/artists/Anirudh_Ravichander_002_20230104094030_500x500.jpg',
      language: 'Tamil',
      category: 'dance',
      listeners: 440000,
      gradient: 'from-red-500/30 to-orange-950/80',
    },
    {
      id: 'tamil-murugan-bhakthi',
      stationId: 'tamil_murugan_bhakthi',
      name: 'Murugan Bhakthi Radio',
      description: 'Kandha sashti kavasam, divine Murugan songs & Amman devotional hymns',
      coverUrl: 'https://c.saavncdn.com/editorial/VenkateswaraSwamyTelugu_20240730054019_500x500.jpg',
      language: 'Tamil',
      category: 'devotional',
      listeners: 390000,
      gradient: 'from-yellow-500/30 to-orange-950/80',
    },
  ],
  Kannada: [
    {
      id: 'kannada-superhits',
      stationId: 'kannada_superhits',
      name: 'Kannada Superhits Radio',
      description: 'All-time Sandalwood blockbusters, melodies & high bass hits',
      coverUrl: 'https://c.saavncdn.com/editorial/KannadaTop50_20231012120000_500x500.jpg',
      language: 'Kannada',
      category: 'featured',
      listeners: 390000,
      gradient: 'from-yellow-500/30 to-red-950/80',
    },
    {
      id: 'kannada-kgf-mass',
      stationId: 'kannada_kgf_mass',
      name: 'KGF Heavy Bass Radio',
      description: 'High energy cinematic anthems & powerhouse BGM by Ravi Basrur',
      coverUrl: 'https://c.saavncdn.com/229/KGF-Chapter-2-Kannada-2022-20220413184646-500x500.jpg',
      language: 'Kannada',
      category: 'dance',
      listeners: 310000,
      gradient: 'from-red-500/30 to-black/80',
    },
    {
      id: 'kannada-melodies',
      stationId: 'kannada_melodies',
      name: 'Sandalwood Melody Magic',
      description: 'Soulful acoustic duets and soothing Kannada love songs',
      coverUrl: 'https://c.saavncdn.com/editorial/charts_Kannada2010s_119421_20240408062837_500x500.jpg',
      language: 'Kannada',
      category: 'mood',
      listeners: 280000,
      gradient: 'from-emerald-500/30 to-teal-950/80',
    },
    {
      id: 'kannada-raghavendra-devotional',
      stationId: 'kannada_raghavendra_devotional',
      name: 'Guru Raghavendra Radio',
      description: 'Divine Rayara stotrams, Haridasa keerthanegalu & pooja hymns',
      coverUrl: 'https://c.saavncdn.com/editorial/VenkateswaraSwamyTelugu_20240730054019_500x500.jpg',
      language: 'Kannada',
      category: 'devotional',
      listeners: 240000,
      gradient: 'from-amber-500/30 to-yellow-950/80',
    },
  ],
  Malayalam: [
    {
      id: 'malayalam-melodies',
      stationId: 'malayalam_melodies',
      name: 'Mollywood Melodies Radio',
      description: 'Soulful Mollywood soundtracks, indie vibes & acoustic tunes',
      coverUrl: 'https://c.saavncdn.com/editorial/MalayalamTop50_20231012120000_500x500.jpg',
      language: 'Malayalam',
      category: 'featured',
      listeners: 340000,
      gradient: 'from-emerald-500/30 to-teal-950/80',
    },
    {
      id: 'malayalam-sushin-vibes',
      stationId: 'malayalam_sushin_vibes',
      name: 'Sushin Shyam Vibe Radio',
      description: 'Aavesham party grooves, electronic hooks & cult Malayalam vibes',
      coverUrl: 'https://c.saavncdn.com/219/Aavesham-Malayalam-2024-20240409163236-500x500.jpg',
      language: 'Malayalam',
      category: 'dance',
      listeners: 380000,
      gradient: 'from-orange-500/30 to-amber-950/80',
    },
    {
      id: 'malayalam-yesudas-evergreen',
      stationId: 'malayalam_yesudas_evergreen',
      name: 'Dr. K.J. Yesudas Evergreen',
      description: 'Celestial golden classics and nostalgic tape recorder memories',
      coverUrl: 'https://c.saavncdn.com/326/Manjummel-Boys-Malayalam-2024-20240126162234-500x500.jpg',
      language: 'Malayalam',
      category: 'retro',
      listeners: 410000,
      gradient: 'from-teal-500/30 to-slate-950/80',
    },
  ],
  Punjabi: [
    {
      id: 'punjabi-fire',
      stationId: 'punjabi_fire',
      name: 'Punjabi Fire Radio',
      description: 'Bhangra bangers, urban drill & chart-topping Punjabi anthems',
      coverUrl: 'https://c.saavncdn.com/editorial/PunjabiTop50_20231012120000_500x500.jpg',
      language: 'Punjabi',
      category: 'featured',
      listeners: 610000,
      gradient: 'from-orange-500/30 to-amber-950/80',
    },
    {
      id: 'punjabi-diljit-vibes',
      stationId: 'punjabi_diljit_vibes',
      name: 'Diljit Dosanjh Anthems',
      description: 'Global stadium hits, peppy beats & smooth Punjabi swag',
      coverUrl: 'https://c.saavncdn.com/artists/Diljit_Dosanjh_004_20221006184545_500x500.jpg',
      language: 'Punjabi',
      category: 'dance',
      listeners: 690000,
      gradient: 'from-red-500/30 to-rose-950/80',
    },
    {
      id: 'punjabi-sidhu-drill',
      stationId: 'punjabi_sidhu_drill',
      name: 'Sidhu Moose Wala Rap Radio',
      description: 'High voltage Punjabi drill, raw hip hop & cult anthems',
      coverUrl: 'https://c.saavncdn.com/artists/Sidhu_Moose_Wala_003_20220530064506_500x500.jpg',
      language: 'Punjabi',
      category: 'dance',
      listeners: 730000,
      gradient: 'from-purple-500/30 to-black/80',
    },
    {
      id: 'punjabi-gurbani',
      stationId: 'punjabi_gurbani',
      name: 'Gurbani & Shabad Kirtan',
      description: 'Peaceful Harmandir Sahib live kirtan, nitnem & divine shabads',
      coverUrl: 'https://c.saavncdn.com/editorial/VenkateswaraSwamyTelugu_20240730054019_500x500.jpg',
      language: 'Punjabi',
      category: 'devotional',
      listeners: 370000,
      gradient: 'from-yellow-500/30 to-orange-950/80',
    },
  ],
  English: [
    {
      id: 'global-billboard',
      stationId: 'global_billboard',
      name: 'Global Billboard Radio',
      description: 'Worldwide Hot 100 hits, electronic vibes & synth-pop anthems',
      coverUrl: 'https://c.saavncdn.com/editorial/EnglishTop50_20231012120000_500x500.jpg',
      language: 'English',
      category: 'featured',
      listeners: 530000,
      gradient: 'from-blue-500/30 to-indigo-950/80',
    },
    {
      id: 'english-alt-pop',
      stationId: 'english_alt_pop',
      name: 'Alt Pop & Midnight Melodies',
      description: 'Atmospheric vocals, indie pop & intimate dark pop tracks',
      coverUrl: 'https://c.saavncdn.com/936/HIT-ME-HARD-AND-SOFT-English-2024-20240517094002-500x500.jpg',
      language: 'English',
      category: 'mood',
      listeners: 460000,
      gradient: 'from-rose-500/30 to-purple-950/80',
    },
    {
      id: 'english-edm-workout',
      stationId: 'english_edm_workout',
      name: 'High Octane EDM & Workout',
      description: 'Festival drops, relentless basslines & adrenaline rush',
      coverUrl: 'https://c.saavncdn.com/editorial/TeluguEDMTelugu_20251006050054_500x500.jpg',
      language: 'English',
      category: 'dance',
      listeners: 420000,
      gradient: 'from-amber-500/30 to-red-950/80',
    },
  ],
  Bengali: [
    {
      id: 'bengali-prime',
      stationId: 'bengali_prime',
      name: 'Bangla Prime Radio',
      description: 'Contemporary Kolkata chartbusters, film soundtracks & melodies',
      coverUrl: 'https://c.saavncdn.com/editorial/TrendingTracks_20240910044733_500x500.jpg',
      language: 'Bengali',
      category: 'featured',
      listeners: 310000,
      gradient: 'from-red-500/30 to-amber-950/80',
    },
    {
      id: 'bengali-rabindra-sangeet',
      stationId: 'bengali_rabindra_sangeet',
      name: 'Rabindra Sangeet Radio',
      description: 'Immortal Tagore compositions, acoustic sitar & soulful vocals',
      coverUrl: 'https://c.saavncdn.com/editorial/TeluguMelodyHits_20220617064213_500x500.jpg',
      language: 'Bengali',
      category: 'retro',
      listeners: 290000,
      gradient: 'from-emerald-500/30 to-teal-950/80',
    },
  ],
  Marathi: [
    {
      id: 'marathi-dhamaka',
      stationId: 'marathi_dhamaka',
      name: 'Marathi Dhamaka Radio',
      description: 'High energy Dhol-Tasha beats, Ajay-Atul masterpieces & Lavani',
      coverUrl: 'https://c.saavncdn.com/editorial/HousePartyTelugu_20260622091856_500x500.jpg',
      language: 'Marathi',
      category: 'featured',
      listeners: 330000,
      gradient: 'from-orange-500/30 to-red-950/80',
    },
    {
      id: 'marathi-vitthal-bhakti',
      stationId: 'marathi_vitthal_bhakti',
      name: 'Vitthal Bhakti Radio',
      description: 'Pandharpur abhangs, Sant Tukaram bhajans & spiritual morning aartis',
      coverUrl: 'https://c.saavncdn.com/editorial/VenkateswaraSwamyTelugu_20240730054019_500x500.jpg',
      language: 'Marathi',
      category: 'devotional',
      listeners: 360000,
      gradient: 'from-amber-500/30 to-yellow-950/80',
    },
  ],
  Bhojpuri: [
    {
      id: 'bhojpuri-superhits',
      stationId: 'bhojpuri_superhits',
      name: 'Bhojpuri Tadka Radio',
      description: 'Viral dance numbers, Pawan Singh & Khesari Lal blockbuster hits',
      coverUrl: 'https://c.saavncdn.com/editorial/Top10DanceDhamaka_20230118120000_500x500.jpg',
      language: 'Bhojpuri',
      category: 'featured',
      listeners: 390000,
      gradient: 'from-red-500/30 to-yellow-950/80',
    },
    {
      id: 'bhojpuri-chhath-pooja',
      stationId: 'bhojpuri_chhath_pooja',
      name: 'Chhath Geeth Radio',
      description: 'Sacred Chhath Puja geeth, Sharda Sinha classics & Surya devotional',
      coverUrl: 'https://c.saavncdn.com/editorial/VenkateswaraSwamyTelugu_20240730054019_500x500.jpg',
      language: 'Bhojpuri',
      category: 'devotional',
      listeners: 310000,
      gradient: 'from-yellow-500/30 to-orange-950/80',
    },
  ],
};

// ── GET /api/radio/stations: Returns station list by language ─────────────────
export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const language = searchParams.get('language') || 'Telugu';

    let stations: RadioStationMetadata[] = [];

    if (language === 'All') {
      stations = Object.values(STATION_CATALOG_DATA).flat();
    } else {
      stations = STATION_CATALOG_DATA[language] || STATION_CATALOG_DATA.Telugu || [];
    }

    return NextResponse.json({
      success: true,
      data: {
        language,
        total: stations.length,
        stations,
      },
    }, {
      headers: {
        'Cache-Control': 'public, s-maxage=21600, stale-while-revalidate=86400',
      },
    });
  } catch (err: any) {
    return NextResponse.json(
      { success: false, error: err?.message || 'Failed to load station catalog' },
      { status: 500 }
    );
  }
}
