-- 1. Create Playback History Table
CREATE TABLE IF NOT EXISTS public.playback_history (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  song_id TEXT NOT NULL,
  artist TEXT,
  genre TEXT,
  action TEXT NOT NULL CHECK (action IN ('play', 'skip', 'like')),
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for fast user history lookups (used by the Python AI engine)
CREATE INDEX IF NOT EXISTS idx_playback_history_user_id ON public.playback_history(user_id);
CREATE INDEX IF NOT EXISTS idx_playback_history_song_id ON public.playback_history(song_id);

-- 2. Create AI Recommendations Table
-- This stores the pre-computed recommendations generated by the Python `implicit` ALS model
CREATE TABLE IF NOT EXISTS public.ai_recommendations (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  recommended_songs JSONB NOT NULL, -- Array of full Song objects
  generated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Enable RLS
ALTER TABLE public.playback_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_recommendations ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies for Playback History
-- Users can only insert and read their own history
CREATE POLICY "Users can insert their own playback history"
ON public.playback_history FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own playback history"
ON public.playback_history FOR SELECT
USING (auth.uid() = user_id);

-- 5. RLS Policies for AI Recommendations
-- Users can only view their own personalized recommendations
CREATE POLICY "Users can view their own recommendations"
ON public.ai_recommendations FOR SELECT
USING (auth.uid() = user_id);

-- Note: The Python engine will use the SUPABASE_SERVICE_ROLE_KEY to bypass RLS 
-- when reading all histories and inserting recommendations.
