export interface RadioStationMetadata {
  id: string;
  stationId: string;
  name: string;
  description: string;
  coverUrl: string;
  language: string;
  category: 'featured' | 'artist' | 'mood' | 'devotional' | 'retro' | 'dance';
  listeners: number;
  gradient: string;
}

export const STATION_CATALOG_DATA: Record<string, RadioStationMetadata[]> = {
  Telugu: [
    {
      id: 'telugu-ultimate-dance-beats',
      stationId: 'telugu_ultimate_dance_beats',
      name: 'Ultimate Dance Beats',
      description: 'High voltage mass beats, EDM remixes & dancefloor bangers',
      coverUrl: 'https://c.saavncdn.com/915/Top-10-Dance-Dhamaka-Hits-Telugu-2025-20251014181041-500x500.jpg',
      language: 'Telugu',
      category: 'dance',
      listeners: 480000,
      gradient: 'from-orange-500/30 to-red-950/80',
    },
    {
      id: 'telugu-hyderabad-heartbeats',
      stationId: 'telugu_hyderabad_heartbeats',
      name: 'Hyderabad Heartbeats',
      description: 'Trending youth anthems, viral hits & city soundtracks',
      coverUrl: 'https://c.saavncdn.com/402/Hyderabad-Butto-Trending-Style-Telugu-2023-20230918142508-500x500.jpg',
      language: 'Telugu',
      category: 'featured',
      listeners: 590000,
      gradient: 'from-rose-500/30 to-pink-950/80',
    },
    {
      id: 'telugu-golden-melodies',
      stationId: 'telugu_golden_melodies',
      name: 'Golden Melodies',
      description: 'Heart-touching melody hits, acoustic chords & vocal magic',
      coverUrl: 'https://c.saavncdn.com/185/Most-Played-Telugu-90S-Melodies-Telugu-2025-20251219143001-500x500.jpg',
      language: 'Telugu',
      category: 'mood',
      listeners: 620000,
      gradient: 'from-emerald-500/30 to-teal-950/80',
    },
    {
      id: 'telugu-long-drive',
      stationId: 'telugu_long_drive',
      name: 'Long Drive Radio',
      description: 'Breezy melodies and road trip vibes for endless highway journeys',
      coverUrl: 'https://c.saavncdn.com/399/Thammudu-2000-500x500.jpg',
      language: 'Telugu',
      category: 'mood',
      listeners: 430000,
      gradient: 'from-cyan-500/30 to-blue-950/80',
    },
    {
      id: 'telugu-saahore',
      stationId: 'telugu_saahore',
      name: 'Saahore',
      description: 'Mass hero elevation tracks, powerhouse BGM & heroism anthems',
      coverUrl: 'https://c.saavncdn.com/101/Sahana-Sahana-From-The-Rajasaab-Telugu-Telugu-2025-20251217171045-500x500.jpg',
      language: 'Telugu',
      category: 'featured',
      listeners: 510000,
      gradient: 'from-amber-500/30 to-red-950/80',
    },
    {
      id: 'telugu-glass-party',
      stationId: 'telugu_glass_party',
      name: 'Glass Party',
      description: 'Full bass weekend party beats, item songs & celebrations',
      coverUrl: 'https://c.saavncdn.com/377/Waltair-Veerayya-Original-Motion-Picture-Soundtrack-Telugu-2023-20230111122627-500x500.jpg',
      language: 'Telugu',
      category: 'dance',
      listeners: 390000,
      gradient: 'from-purple-500/30 to-indigo-950/80',
    },
    {
      id: 'telugu-mesmerizing-90s',
      stationId: 'telugu_mesmerizing_90s',
      name: 'Mesmerizing 90s',
      description: 'Cassette era nostalgic classics by SPB, Chithra & Mani Sharma',
      coverUrl: 'https://c.saavncdn.com/042/Devadai-1997-500x500.jpg',
      language: 'Telugu',
      category: 'retro',
      listeners: 530000,
      gradient: 'from-teal-500/30 to-slate-950/80',
    },
    {
      id: 'telugu-millennium-hits',
      stationId: 'telugu_millennium_hits',
      name: 'Millennium Hits',
      description: 'The definitive 2000s Telugu anthems and chartbusters',
      coverUrl: 'https://c.saavncdn.com/298/Aarya-2-Telugu-2009-20190822135933-500x500.jpg',
      language: 'Telugu',
      category: 'retro',
      listeners: 460000,
      gradient: 'from-indigo-500/30 to-slate-950/80',
    },
    {
      id: 'telugu-retro-spin',
      stationId: 'telugu_retro_spin',
      name: 'Retro Spin',
      description: 'Vintage 70s & 80s timeless melodies and evergreen golden hits',
      coverUrl: 'https://c.saavncdn.com/662/Kamals-Classics-Telugu-Telugu-2019-20191031120426-500x500.jpg',
      language: 'Telugu',
      category: 'retro',
      listeners: 340000,
      gradient: 'from-yellow-500/30 to-amber-950/80',
    },
    {
      id: 'telugu-remix-mazaa',
      stationId: 'telugu_remix_mazaa',
      name: 'Remix Mazaa',
      description: 'Club mixes, trap drops & non-stop high energy bass reworks',
      coverUrl: 'https://c.saavncdn.com/075/Nadakallo-Nadaka-DJ-Remix-Song-Telugu-2024-20240328203121-500x500.jpg',
      language: 'Telugu',
      category: 'dance',
      listeners: 310000,
      gradient: 'from-fuchsia-500/30 to-pink-950/80',
    },
    {
      id: 'telugu-mi-inti-lakshmi',
      stationId: 'telugu_mi_inti_lakshmi',
      name: 'Mi Inti Lakshmi',
      description: 'Auspicious Friday morning devotional stotras and goddess hymns',
      coverUrl: 'https://c.saavncdn.com/830/Telugu-Devotional-Songs-2021-Telugu-2021-20211208135756-500x500.jpg',
      language: 'Telugu',
      category: 'devotional',
      listeners: 290000,
      gradient: 'from-yellow-400/30 to-orange-950/80',
    },
    {
      id: 'telugu-ayyappa',
      stationId: 'telugu_ayyappa',
      name: 'Ayyappa Swamy Radio',
      description: 'Padi Pooja devotional songs, Harivarasanam and pilgrimage chants',
      coverUrl: 'https://c.saavncdn.com/827/Ayyappa-Devotional-Songs-Telugu-2020-20201209232741-500x500.jpg',
      language: 'Telugu',
      category: 'devotional',
      listeners: 270000,
      gradient: 'from-amber-600/30 to-stone-950/80',
    },
    {
      id: 'telugu-om-sai-ram',
      stationId: 'telugu_om_sai_ram',
      name: 'Om Sai Ram',
      description: 'Divine Shirdi Sai Baba Bhajans, kakad aartis and evening prayers',
      coverUrl: 'https://c.saavncdn.com/000/Sri-Shirdi-Sai-Baba-Mahathyam-Telugu-1985-20220609233743-500x500.jpg',
      language: 'Telugu',
      category: 'devotional',
      listeners: 250000,
      gradient: 'from-orange-400/30 to-amber-950/80',
    },
    {
      id: 'telugu-govinda-govinda',
      stationId: 'telugu_govinda_govinda',
      name: 'Govinda Govinda',
      description: 'Tirumala Balaji Venkateswara suprabhatam and Annamayya songs',
      coverUrl: 'https://c.saavncdn.com/213/Sri-Venkateswara-Swamy-Suprabatam-Telugu-2024-20240522135722-500x500.jpg',
      language: 'Telugu',
      category: 'devotional',
      listeners: 360000,
      gradient: 'from-yellow-400/30 to-yellow-950/80',
    },
  ],
  Hindi: [
    {
      id: 'hindi-trending-today',
      stationId: 'hindi_trending_today',
      name: 'Hindi Trending',
      description: "Today's biggest Bollywood & Pop chartbusters",
      coverUrl: 'https://c.saavncdn.com/675/Trending-Love-Songs-Hindi-2026-20260506185328-500x500.jpg',
      language: 'Hindi',
      category: 'featured',
      listeners: 820000,
      gradient: 'from-red-500/30 to-rose-950/80',
    },
    {
      id: 'hindi-romantic-melodies',
      stationId: 'hindi_romantic_melodies',
      name: 'Love Melodies',
      description: 'Soul-stirring romantic Bollywood love songs',
      coverUrl: 'https://c.saavncdn.com/238/Romantic-Classics-Hits-Hindi-2026-20260529163838-500x500.jpg',
      language: 'Hindi',
      category: 'mood',
      listeners: 740000,
      gradient: 'from-pink-500/30 to-red-950/80',
    },
    {
      id: 'hindi-bollywood-dance',
      stationId: 'hindi_bollywood_dance',
      name: 'Bollywood Dance',
      description: 'High energy party bangers and dance club tracks',
      coverUrl: 'https://c.saavncdn.com/148/Lungi-Dance-2013-500x500.jpg',
      language: 'Hindi',
      category: 'dance',
      listeners: 610000,
      gradient: 'from-amber-500/30 to-orange-950/80',
    },
    {
      id: 'hindi-90s-magic',
      stationId: 'hindi_90s_magic',
      name: '90s Magic',
      description: 'Nostalgic golden hits from the 1990s Bollywood era',
      coverUrl: 'https://c.saavncdn.com/588/Dilwale-Dulhania-Le-Jayenge-Hindi-1995-20171114-500x500.jpg',
      language: 'Hindi',
      category: 'retro',
      listeners: 690000,
      gradient: 'from-teal-500/30 to-blue-950/80',
    },
    {
      id: 'hindi-bhakti-sagar',
      stationId: 'hindi_bhakti_sagar',
      name: 'Bhakti Sagar',
      description: 'Peaceful morning devotional aartis and chants',
      coverUrl: 'https://c.saavncdn.com/205/Jagjanani-Maa-Devotional-Bhajan-Hindi-2025-20250825131013-500x500.jpg',
      language: 'Hindi',
      category: 'devotional',
      listeners: 450000,
      gradient: 'from-yellow-500/30 to-orange-950/80',
    },
  ],
  Tamil: [
    {
      id: 'tamil-trending-hits',
      stationId: 'tamil_trending_hits',
      name: 'Tamil Trending',
      description: 'Viral Kollywood numbers and top streaming Tamil tracks',
      coverUrl: 'https://c.saavncdn.com/804/Trending-Tamil-2025-20250922073957-500x500.jpg',
      language: 'Tamil',
      category: 'featured',
      listeners: 680000,
      gradient: 'from-cyan-500/30 to-blue-950/80',
    },
    {
      id: 'tamil-anirudh-vibes',
      stationId: 'tamil_anirudh_vibes',
      name: 'Rockstar Anirudh',
      description: 'High-octane mass beats and soul melodies by Anirudh',
      coverUrl: 'https://c.saavncdn.com/484/Raga-of-Revenge-From-DC-Tamil-2026-20260515180436-500x500.jpg',
      language: 'Tamil',
      category: 'dance',
      listeners: 720000,
      gradient: 'from-purple-500/30 to-indigo-950/80',
    },
    {
      id: 'tamil-ar-rahman-classics',
      stationId: 'tamil_ar_rahman_classics',
      name: 'Isaipuyal Rahman',
      description: 'Timeless masterpieces and orchestrations by A.R. Rahman',
      coverUrl: 'https://c.saavncdn.com/289/Pathu-Thala-Original-Motion-Picture-Soundtrack-Tamil-2023-20230320144505-500x500.jpg',
      language: 'Tamil',
      category: 'mood',
      listeners: 650000,
      gradient: 'from-emerald-500/30 to-teal-950/80',
    },
    {
      id: 'tamil-90s-nostalgia',
      stationId: 'tamil_90s_nostalgia',
      name: '90s Tamil Nostalgia',
      description: 'Evergreen 90s audio tracks from Ilaiyaraaja & Deva',
      coverUrl: 'https://c.saavncdn.com/042/Devadai-1997-500x500.jpg',
      language: 'Tamil',
      category: 'retro',
      listeners: 520000,
      gradient: 'from-amber-500/30 to-red-950/80',
    },
    {
      id: 'tamil-devotional',
      stationId: 'tamil_devotional',
      name: 'Tamil Bakthi',
      description: 'Lord Murugan and Amman sacred morning prayers',
      coverUrl: 'https://c.saavncdn.com/235/Murugan-Devotional-Tamil-1966-20181105-500x500.jpg',
      language: 'Tamil',
      category: 'devotional',
      listeners: 390000,
      gradient: 'from-yellow-500/30 to-orange-950/80',
    },
  ],
  Kannada: [
    {
      id: 'kannada-top-hits',
      stationId: 'kannada_top_hits',
      name: 'Kannada Top Hits',
      description: 'Sandalwood chartbusters and trending tracks',
      coverUrl: 'https://c.saavncdn.com/501/Trendingg-From-Wild-Tiger-Safari-Kannada-2026-20260217182903-500x500.jpg',
      language: 'Kannada',
      category: 'featured',
      listeners: 420000,
      gradient: 'from-red-500/30 to-amber-950/80',
    },
    {
      id: 'kannada-melodies',
      stationId: 'kannada_melodies',
      name: 'Kannada Melodies',
      description: 'Soulful acoustic Kannada love anthems',
      coverUrl: 'https://c.saavncdn.com/900/Sandalwood-Emotional-Romantic-Superhits-Kannada-2025-20251107191052-500x500.jpg',
      language: 'Kannada',
      category: 'mood',
      listeners: 380000,
      gradient: 'from-emerald-500/30 to-teal-950/80',
    },
    {
      id: 'kannada-retro',
      stationId: 'kannada_retro',
      name: 'Vintage Kannada',
      description: 'Evergreen Sandalwood classics of Dr. Rajkumar & SPB',
      coverUrl: 'https://c.saavncdn.com/996/Om-Kannada-1995-20200806160633-500x500.jpg',
      language: 'Kannada',
      category: 'retro',
      listeners: 310000,
      gradient: 'from-blue-500/30 to-indigo-950/80',
    },
  ],
  Malayalam: [
    {
      id: 'malayalam-top-hits',
      stationId: 'malayalam_top_hits',
      name: 'Mollywood Top Hits',
      description: 'Fresh Mollywood chartbusters and indie vibes',
      coverUrl: 'https://c.saavncdn.com/208/Top-Trending-Love-Songs-Malayalam-2026-20260212195859-500x500.jpg',
      language: 'Malayalam',
      category: 'featured',
      listeners: 490000,
      gradient: 'from-teal-500/30 to-emerald-950/80',
    },
    {
      id: 'malayalam-soul-melodies',
      stationId: 'malayalam_soul_melodies',
      name: 'Kerala Melodies',
      description: 'Lush melodies, rain songs & heart-touching lyrics',
      coverUrl: 'https://c.saavncdn.com/993/Malayalam-Movie-Romantic-Collections-Malayalam-2015-20260625145447-500x500.jpg',
      language: 'Malayalam',
      category: 'mood',
      listeners: 430000,
      gradient: 'from-blue-500/30 to-cyan-950/80',
    },
  ],
  Punjabi: [
    {
      id: 'punjabi-mass-bangers',
      stationId: 'punjabi_mass_bangers',
      name: 'Punjabi Bangers',
      description: 'High-energy Dhol, Bhangra & trap pop hits',
      coverUrl: 'https://c.saavncdn.com/245/Hass-Hass-English-2023-20231026170517-500x500.jpg',
      language: 'Punjabi',
      category: 'dance',
      listeners: 560000,
      gradient: 'from-amber-500/30 to-orange-950/80',
    },
    {
      id: 'punjabi-romance',
      stationId: 'punjabi_romance',
      name: 'Punjabi Romance',
      description: 'Heartwarming acoustic and melodic Punjabi love tunes',
      coverUrl: 'https://c.saavncdn.com/678/Romantic-Amli-Punjabi-2026-20260802103440-500x500.jpg',
      language: 'Punjabi',
      category: 'mood',
      listeners: 480000,
      gradient: 'from-pink-500/30 to-rose-950/80',
    },
  ],
  English: [
    {
      id: 'english-global-top',
      stationId: 'english_global_top',
      name: 'Global Hits',
      description: 'The biggest international billboard chart-toppers',
      coverUrl: 'https://c.saavncdn.com/499/Discover-2025-Popular-Global-Picks-Korean-2025-20260213034555-500x500.jpg',
      language: 'English',
      category: 'featured',
      listeners: 890000,
      gradient: 'from-indigo-500/30 to-purple-950/80',
    },
    {
      id: 'english-chill-vibes',
      stationId: 'english_chill_vibes',
      name: 'Chill Acoustic',
      description: 'Relaxing lo-fi, acoustic pop and mellow evening vibes',
      coverUrl: 'https://c.saavncdn.com/709/Acoustic-Chill-English-2026-20260402053459-500x500.jpg',
      language: 'English',
      category: 'mood',
      listeners: 670000,
      gradient: 'from-teal-500/30 to-slate-950/80',
    },
  ],
};

export function getStationCatalog(language = 'Telugu'): RadioStationMetadata[] {
  if (language === 'All') {
    const all: RadioStationMetadata[] = [];
    Object.values(STATION_CATALOG_DATA).forEach((list) => all.push(...list));
    return all;
  }
  const norm = language.charAt(0).toUpperCase() + language.slice(1).toLowerCase();
  return STATION_CATALOG_DATA[norm] || STATION_CATALOG_DATA['Telugu'] || [];
}
