export interface RadioStationMetadata {
  id: string;
  stationId: string;
  name: string;
  description: string;
  coverUrl: string;
  language: string;
  category: 'featured' | 'artist' | 'mood' | 'devotional' | 'retro' | 'dance';
  listeners: number;
  gradient: string;
}

export const STATION_CATALOG_DATA: Record<string, RadioStationMetadata[]> = {
  Telugu: [
    {
      id: 'telugu-ultimate-dance-beats',
      stationId: 'telugu_ultimate_dance_beats',
      name: 'Ultimate Dance Beats',
      description: 'High voltage mass beats, EDM remixes & dancefloor bangers',
      coverUrl: 'https://c.saavncdn.com/editorial/TeluguEDMTelugu_20251006050054_500x500.jpg',
      language: 'Telugu',
      category: 'dance',
      listeners: 480000,
      gradient: 'from-orange-500/30 to-red-950/80',
    },
    {
      id: 'telugu-hyderabad-heartbeats',
      stationId: 'telugu_hyderabad_heartbeats',
      name: 'Hyderabad Heartbeats',
      description: 'Trending youth anthems, viral hits & city soundtracks',
      coverUrl: 'https://c.saavncdn.com/editorial/TrendingTeluguSongs_20260529073729_500x500.jpg',
      language: 'Telugu',
      category: 'featured',
      listeners: 590000,
      gradient: 'from-rose-500/30 to-pink-950/80',
    },
    {
      id: 'telugu-golden-melodies',
      stationId: 'telugu_golden_melodies',
      name: 'Golden Melodies',
      description: 'Heart-touching melody hits, acoustic chords & vocal magic',
      coverUrl: 'https://c.saavncdn.com/editorial/TeluguMelodyHits_20220617064213_500x500.jpg',
      language: 'Telugu',
      category: 'mood',
      listeners: 620000,
      gradient: 'from-emerald-500/30 to-teal-950/80',
    },
    {
      id: 'telugu-long-drive',
      stationId: 'telugu_long_drive',
      name: 'Long Drive Radio',
      description: 'Breezy melodies and road trip vibes for endless highway journeys',
      coverUrl: 'https://c.saavncdn.com/editorial/TravelCheddam_20251205063518_500x500.jpg',
      language: 'Telugu',
      category: 'mood',
      listeners: 430000,
      gradient: 'from-cyan-500/30 to-blue-950/80',
    },
    {
      id: 'telugu-saahore',
      stationId: 'telugu_saahore',
      name: 'Saahore',
      description: 'Mass hero elevation tracks, powerhouse BGM & heroism anthems',
      coverUrl: 'https://c.saavncdn.com/editorial/Let_sPlayPrabhasTelugu_20240628094353_500x500.jpg',
      language: 'Telugu',
      category: 'featured',
      listeners: 510000,
      gradient: 'from-amber-500/30 to-red-950/80',
    },
    {
      id: 'telugu-glass-party',
      stationId: 'telugu_glass_party',
      name: 'Glass Party',
      description: 'Full bass weekend party beats, item songs & celebrations',
      coverUrl: 'https://c.saavncdn.com/editorial/HousePartyTelugu_20260622091856_500x500.jpg',
      language: 'Telugu',
      category: 'dance',
      listeners: 390000,
      gradient: 'from-purple-500/30 to-indigo-950/80',
    },
    {
      id: 'telugu-mesmerizing-90s',
      stationId: 'telugu_mesmerizing_90s',
      name: 'Mesmerizing 90s',
      description: 'Cassette era nostalgic classics by SPB, Chithra & Mani Sharma',
      coverUrl: 'https://c.saavncdn.com/editorial/charts_Telugu1990s_157621_20240408063237_500x500.jpg',
      language: 'Telugu',
      category: 'retro',
      listeners: 530000,
      gradient: 'from-teal-500/30 to-slate-950/80',
    },
    {
      id: 'telugu-millennium-hits',
      stationId: 'telugu_millennium_hits',
      name: 'Millennium Hits',
      description: 'The definitive 2000s Telugu anthems and chartbusters',
      coverUrl: 'https://c.saavncdn.com/editorial/Bestof2000sTelugu_20231110052328_500x500.jpg',
      language: 'Telugu',
      category: 'retro',
      listeners: 460000,
      gradient: 'from-indigo-500/30 to-slate-950/80',
    },
    {
      id: 'telugu-retro-spin',
      stationId: 'telugu_retro_spin',
      name: 'Retro Spin',
      description: 'Vintage 70s & 80s timeless melodies and evergreen golden hits',
      coverUrl: 'https://c.saavncdn.com/editorial/Telugu1980s_20220311090123_500x500.jpg',
      language: 'Telugu',
      category: 'retro',
      listeners: 340000,
      gradient: 'from-yellow-500/30 to-amber-950/80',
    },
    {
      id: 'telugu-remix-mazaa',
      stationId: 'telugu_remix_mazaa',
      name: 'Remix Mazaa',
      description: 'Club mixes, trap drops & non-stop high energy bass reworks',
      coverUrl: 'https://c.saavncdn.com/editorial/TeluguPartyMix_20240412104523_500x500.jpg',
      language: 'Telugu',
      category: 'dance',
      listeners: 310000,
      gradient: 'from-fuchsia-500/30 to-pink-950/80',
    },
    {
      id: 'telugu-mi-inti-lakshmi',
      stationId: 'telugu_mi_inti_lakshmi',
      name: 'Mi Inti Lakshmi',
      description: 'Auspicious Friday morning devotional stotras and goddess hymns',
      coverUrl: 'https://c.saavncdn.com/editorial/SriLakshmiDeviBhakthiGeethalu_20231019053744_500x500.jpg',
      language: 'Telugu',
      category: 'devotional',
      listeners: 290000,
      gradient: 'from-yellow-400/30 to-orange-950/80',
    },
    {
      id: 'telugu-ayyappa',
      stationId: 'telugu_ayyappa',
      name: 'Ayyappa Swamy Radio',
      description: 'Padi Pooja devotional songs, Harivarasanam and pilgrimage chants',
      coverUrl: 'https://c.saavncdn.com/editorial/AyyappaDevotionalSongsTelugu_20231117101732_500x500.jpg',
      language: 'Telugu',
      category: 'devotional',
      listeners: 270000,
      gradient: 'from-amber-600/30 to-stone-950/80',
    },
    {
      id: 'telugu-om-sai-ram',
      stationId: 'telugu_om_sai_ram',
      name: 'Om Sai Ram',
      description: 'Shirdi Sai Baba bhajans, kakad aarti & peaceful meditation prayers',
      coverUrl: 'https://c.saavncdn.com/editorial/ShirdiSaiBabaBhakthiGeethalu_20230623055928_500x500.jpg',
      language: 'Telugu',
      category: 'devotional',
      listeners: 350000,
      gradient: 'from-orange-400/30 to-amber-950/80',
    },
    {
      id: 'telugu-nithyaardhana',
      stationId: 'telugu_nithyaardhana',
      name: 'Nithyaardhana',
      description: 'Daily spiritual chants, Venkateswara Suprabhatam & morning peace',
      coverUrl: 'https://c.saavncdn.com/editorial/VenkateswaraSwamyBhakthiGeethalu_20230602055621_500x500.jpg',
      language: 'Telugu',
      category: 'devotional',
      listeners: 410000,
      gradient: 'from-emerald-400/30 to-teal-950/80',
    },
  ],
  Hindi: [
    {
      id: 'hindi-trending-today',
      stationId: 'hindi_trending_today',
      name: 'Trending Hindi Hits',
      description: 'Top Bollywood chartbusters and viral pop sensations',
      coverUrl: 'https://c.saavncdn.com/editorial/TrendingTodayHindi_20260424075133_500x500.jpg',
      language: 'Hindi',
      category: 'featured',
      listeners: 890000,
      gradient: 'from-rose-500/30 to-red-950/80',
    },
    {
      id: 'hindi-romantic-station',
      stationId: 'hindi_romantic_station',
      name: 'Ishqiyaan Melodies',
      description: 'Acoustic love ballads, romantic duets and soulful strings',
      coverUrl: 'https://c.saavncdn.com/editorial/RomanticHitsHindi_20240322104523_500x500.jpg',
      language: 'Hindi',
      category: 'mood',
      listeners: 780000,
      gradient: 'from-pink-500/30 to-purple-950/80',
    },
    {
      id: 'hindi-dance-masti',
      stationId: 'hindi_dance_masti',
      name: 'Bollywood Club Beats',
      description: 'Nonstop party mixes, high-tempo Punjabi crossovers and wedding bangers',
      coverUrl: 'https://c.saavncdn.com/editorial/BollywoodDanceHits_20240412104523_500x500.jpg',
      language: 'Hindi',
      category: 'dance',
      listeners: 640000,
      gradient: 'from-orange-500/30 to-amber-950/80',
    },
    {
      id: 'hindi-90s-nostalgia',
      stationId: 'hindi_90s_nostalgia',
      name: '90s Magic Cassette',
      description: 'Kumar Sanu, Alka Yagnik and Udit Narayan classic golden hits',
      coverUrl: 'https://c.saavncdn.com/editorial/Bestof90sHindi_20231110052328_500x500.jpg',
      language: 'Hindi',
      category: 'retro',
      listeners: 720000,
      gradient: 'from-cyan-500/30 to-blue-950/80',
    },
    {
      id: 'hindi-devotional-bhakti',
      stationId: 'hindi_devotional_bhakti',
      name: 'Bhakti Sagar',
      description: 'Peaceful morning aartis, Hanuman Chalisa & divine bhajans',
      coverUrl: 'https://c.saavncdn.com/editorial/BhaktiSagarHindi_20230602055621_500x500.jpg',
      language: 'Hindi',
      category: 'devotional',
      listeners: 510000,
      gradient: 'from-amber-400/30 to-orange-950/80',
    },
  ],
  Tamil: [
    {
      id: 'tamil-mass-beats',
      stationId: 'tamil_mass_beats',
      name: 'Kuthu Fire Beats',
      description: 'Anirudh, Yuvan & Harris Jayaraj high energy dance numbers',
      coverUrl: 'https://c.saavncdn.com/editorial/TrendingTamilSongs_20260529073729_500x500.jpg',
      language: 'Tamil',
      category: 'dance',
      listeners: 610000,
      gradient: 'from-amber-500/30 to-red-950/80',
    },
    {
      id: 'tamil-melody-kings',
      stationId: 'tamil_melody_kings',
      name: 'Kaadhal Melodies',
      description: 'Soulful AR Rahman & Ilaiyaraaja acoustic love symphonies',
      coverUrl: 'https://c.saavncdn.com/editorial/TamilMelodyHits_20220617064213_500x500.jpg',
      language: 'Tamil',
      category: 'mood',
      listeners: 690000,
      gradient: 'from-teal-500/30 to-emerald-950/80',
    },
    {
      id: 'tamil-retro-golden',
      stationId: 'tamil_retro_golden',
      name: 'Vintage Tamil Nostalgia',
      description: 'SPB and Janaki evergreen 80s and 90s cinema classics',
      coverUrl: 'https://c.saavncdn.com/editorial/charts_Tamil1990s_157621_20240408063237_500x500.jpg',
      language: 'Tamil',
      category: 'retro',
      listeners: 430000,
      gradient: 'from-purple-500/30 to-indigo-950/80',
    },
  ],
};

export function getStationCatalog(language = 'Telugu'): RadioStationMetadata[] {
  const norm = language.charAt(0).toUpperCase() + language.slice(1).toLowerCase();
  return STATION_CATALOG_DATA[norm] || STATION_CATALOG_DATA['Telugu'] || [];
}
